version: "3.8"
services:
  yoga-react:
    image: yoga-react
    stdin_open: true
    restart: always
    ports:
      - "3000:3000"
    networks:
      - mern-app
  yoga-api-server:
    image: yoga-api-server
    restart: always
    ports:
      - "8000:8000"
    networks:
      - mern-app
    depends_on:
      - mongo
  mongo:
    image: mongo:4.0.28-xenial
    restart: always
    ports:
      - "27017:27017"
    networks:
      - mern-app
    volumes:
      - mongo-data:/data/db
networks:
  mern-app:
    driver: bridge
volumes:
  mongo-data:
    driver: local
